# Generated by Django 4.1.4 on 2023-10-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fightRezult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezult', models.TextField()),
                ('time', models.DateField()),
                ('round_count', models.IntegerField()),
                ('first_pokemon', models.TextField()),
                ('second_pokemon', models.TextField()),
                ('winner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pokemonfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=50)),
                ('comment', models.TextField(max_length=200)),
                ('pokemon_name', models.TextField()),
                ('star', models.IntegerField()),
            ],
        ),
    ]
