# Generated by Django 4.1.4 on 2023-10-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fightrezult',
            old_name='rezult',
            new_name='text',
        ),
    ]
