# Generated by Django 4.1.4 on 2023-12-01 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemons', '0002_pokemonfeedback_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonfeedback',
            name='user_id',
        ),
        migrations.AddField(
            model_name='fightrezult',
            name='user_id',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
