# Generated by Django 4.1.4 on 2023-10-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_rename_rezult_fightrezult_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fightrezult',
            old_name='text',
            new_name='rezult',
        ),
    ]
