# Generated by Django 4.0 on 2023-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_rename_text_fightrezult_rezult'),
    ]

    operations = [
        migrations.CreateModel(
            name='pokemonfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.TextField(max_length=50)),
                ('comment', models.TextField(max_length=200)),
                ('pokemon_name', models.TextField()),
            ],
        ),
    ]
