version: "3.11.2"
services:
  ortpo_db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_DB: postgres

  ortpo_web:
    #container_name: otrpo_api
    build: 
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /otrpo-1/otrpo/firststep/manage.py migrate --noinput && 
        python /otrpo-1/otrpo/firststep/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/otrpo-1/otrpo/firststep
    ports:
      - "8000:8000"
    depends_on:
      - ortpo_db
  ftp:
    build: .
    container_name: ftp
    command: bash -c "cd pokemons/ftp_files/;python ftp.py;"
    volumes:
      - .:/pokemons/ftp_files
    depends_on:
      - ortpo_web
    ports:
      - "2000:2000"

volumes:
  postgres_data:
    