name: test_Django

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.2
      
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Install dependencies
      working-directory: ./otrpo/firststep/
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2
        pip install -r requirements.txt
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '15' 
      
    - name: Django Testing
      working-directory: ./otrpo/firststep/
      run: |
        python manage.py test
    - name: Django Testing
      working-directory: ./otrpo/firststep/
      run: |
        python3 manage.py test
