name: Docker Login

on:
  push:
    branches:
      - main

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: astellhero/otrpo:test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
